apiVersion: v1
kind: Service
metadata:
  name: klawty
  labels:
    app: klawty
spec:
  type: ClusterIP
  selector:
    app: klawty
  ports:
    - name: gateway
      port: 2508
      targetPort: 2508
      protocol: TCP
