export const browserCoreExamples = [
  "klawty browser status",
  "klawty browser start",
  "klawty browser stop",
  "klawty browser tabs",
  "klawty browser open https://example.com",
  "klawty browser focus abcd1234",
  "klawty browser close abcd1234",
  "klawty browser screenshot",
  "klawty browser screenshot --full-page",
  "klawty browser screenshot --ref 12",
  "klawty browser snapshot",
  "klawty browser snapshot --format aria --limit 200",
  "klawty browser snapshot --efficient",
  "klawty browser snapshot --labels",
];

export const browserActionExamples = [
  "klawty browser navigate https://example.com",
  "klawty browser resize 1280 720",
  "klawty browser click 12 --double",
  'klawty browser type 23 "hello" --submit',
  "klawty browser press Enter",
  "klawty browser hover 44",
  "klawty browser drag 10 11",
  "klawty browser select 9 OptionA OptionB",
  "klawty browser upload /tmp/klawty/uploads/file.pdf",
  'klawty browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "klawty browser dialog --accept",
  'klawty browser wait --text "Done"',
  "klawty browser evaluate --fn '(el) => el.textContent' --ref 7",
  "klawty browser console --level error",
  "klawty browser pdf",
];
